package io

import (
	"encoding/xml"
	"ez-utils/src/create/tv/core"
	"fmt"
	"os"
	"time"
)

// VehicleExporter handles exporting vehicles to MATSim XML format
type VehicleExporter struct {
	VehicleTypes []*core.VehicleType
	Vehicles     []*core.Vehicle
}

// NewVehicleExporter creates a new vehicle exporter
func NewVehicleExporter(vehicleTypes []*core.VehicleType, vehicles []*core.Vehicle) *VehicleExporter {
	return &VehicleExporter{
		VehicleTypes: vehicleTypes,
		Vehicles:     vehicles,
	}
}

// Export writes the vehicles to a MATSim transitVehicles XML file
func (ve *VehicleExporter) Export(filename string) error {
	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer file.Close()

	// Write XML header with proper encoding
	file.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	file.WriteString("\n")
	file.WriteString(`<!DOCTYPE vehicleDefinitions SYSTEM "http://www.matsim.org/files/dtd/vehicleDefinitions_v1.0.dtd">`)
	file.WriteString("\n")
	file.WriteString("<!-- Generated by ez-utils Transit Vehicle Manager -->\n")
	file.WriteString(fmt.Sprintf("<!-- Generated on: %s -->\n", time.Now().Format("2006-01-02 15:04:05")))
	file.WriteString(fmt.Sprintf("<!-- Vehicle Types: %d, Vehicles: %d -->\n", len(ve.VehicleTypes), len(ve.Vehicles)))
	file.WriteString("\n")

	// Create root element
	root := VehicleDefinitions{
		XMLNs:             "http://www.matsim.org/files/dtd",
		XMLNsXsi:          "http://www.w3.org/2001/XMLSchema-instance",
		XsiSchemaLocation: "http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v1.0.xsd",
	}

	// Add vehicle types (already in order since using slice)
	for _, vt := range ve.VehicleTypes {
		xmlType := XMLVehicleType{
			ID:          vt.ID,
			Description: vt.Description,
			Capacity: XMLCapacity{
				Seats: XMLSeats{
					Persons: vt.Capacity.Seats,
				},
				StandingRoom: XMLStandingRoom{
					Persons: vt.Capacity.Standing,
				},
			},
			Length:                  vt.Length,
			Width:                   vt.Width,
			AccessTime:              vt.AccessTime,
			EgressTime:              vt.EgressTime,
			DoorOperation:           vt.DoorOperation,
			PassengerCarEquivalents: vt.PassengerCarEquivalents,
		}
		root.VehicleTypes = append(root.VehicleTypes, xmlType)
	}

	// Add vehicles (already in order since using slice)
	for _, v := range ve.Vehicles {
		xmlVehicle := XMLVehicle{
			ID:   v.ID,
			Type: v.TypeID,
		}
		root.Vehicles = append(root.Vehicles, xmlVehicle)
	}

	// Marshal to XML with proper indentation
	encoder := xml.NewEncoder(file)
	encoder.Indent("", "  ")
	if err := encoder.Encode(root); err != nil {
		return fmt.Errorf("failed to encode XML: %w", err)
	}

	// Add final newline for proper file ending
	file.WriteString("\n")

	return nil
}

// XML structures for MATSim vehicle definitions

type VehicleDefinitions struct {
	XMLName           xml.Name         `xml:"vehicleDefinitions"`
	XMLNs             string           `xml:"xmlns,attr"`
	XMLNsXsi          string           `xml:"xmlns:xsi,attr"`
	XsiSchemaLocation string           `xml:"xsi:schemaLocation,attr"`
	VehicleTypes      []XMLVehicleType `xml:"vehicleType"`
	Vehicles          []XMLVehicle     `xml:"vehicle"`
}

type XMLVehicleType struct {
	ID                      string      `xml:"id,attr"`
	Description             string      `xml:"description"`
	Capacity                XMLCapacity `xml:"capacity"`
	Length                  float64     `xml:"length"`
	Width                   float64     `xml:"width"`
	AccessTime              float64     `xml:"accessTime"`
	EgressTime              float64     `xml:"egressTime"`
	DoorOperation           string      `xml:"doorOperation,attr"`
	PassengerCarEquivalents float64     `xml:"passengerCarEquivalents"`
}

type XMLCapacity struct {
	Seats        XMLSeats        `xml:"seats"`
	StandingRoom XMLStandingRoom `xml:"standingRoom"`
}

type XMLSeats struct {
	Persons int `xml:"persons,attr"`
}

type XMLStandingRoom struct {
	Persons int `xml:"persons,attr"`
}

type XMLVehicle struct {
	ID   string `xml:"id,attr"`
	Type string `xml:"type,attr"`
}

// SaveToFile is a convenience function that takes a VehicleManager and saves its data to a file
func SaveToFile(manager *core.VehicleManager, filePath string) error {
	exporter := NewVehicleExporter(manager.VehicleTypes, manager.Vehicles)
	if err := exporter.Export(filePath); err != nil {
		return fmt.Errorf("failed to save vehicles: %w", err)
	}

	manager.HasChanges = false
	return nil
}
