// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPerson(arg1, arg2) {
  return window['go']['gui']['App']['AddPerson'](arg1, arg2);
}

export function CheckProcessingStatus(arg1) {
  return window['go']['gui']['App']['CheckProcessingStatus'](arg1);
}

export function DeletePerson(arg1, arg2) {
  return window['go']['gui']['App']['DeletePerson'](arg1, arg2);
}

export function DeleteProcess(arg1) {
  return window['go']['gui']['App']['DeleteProcess'](arg1);
}

export function GetPopulation(arg1) {
  return window['go']['gui']['App']['GetPopulation'](arg1);
}

export function GetProcesses() {
  return window['go']['gui']['App']['GetProcesses']();
}

export function GetProcessesByFile(arg1) {
  return window['go']['gui']['App']['GetProcessesByFile'](arg1);
}

export function GetStartupFile() {
  return window['go']['gui']['App']['GetStartupFile']();
}

export function ProcessFile(arg1) {
  return window['go']['gui']['App']['ProcessFile'](arg1);
}

export function UpdatePersonPlan(arg1, arg2, arg3) {
  return window['go']['gui']['App']['UpdatePersonPlan'](arg1, arg2, arg3);
}
