// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProcessingStatus(arg1) {
  return window['go']['gui']['App']['CheckProcessingStatus'](arg1);
}

export function ExecuteAction(arg1) {
  return window['go']['gui']['App']['ExecuteAction'](arg1);
}

export function ExitApplication() {
  return window['go']['gui']['App']['ExitApplication']();
}

export function ExportNetworkFile(arg1, arg2, arg3) {
  return window['go']['gui']['App']['ExportNetworkFile'](arg1, arg2, arg3);
}

export function ExportPTFile(arg1, arg2) {
  return window['go']['gui']['App']['ExportPTFile'](arg1, arg2);
}

export function ExportPTSubset(arg1, arg2, arg3) {
  return window['go']['gui']['App']['ExportPTSubset'](arg1, arg2, arg3);
}

export function GetDebugLogs() {
  return window['go']['gui']['App']['GetDebugLogs']();
}

export function GetPTDepartures(arg1, arg2) {
  return window['go']['gui']['App']['GetPTDepartures'](arg1, arg2);
}

export function GetPTLine(arg1, arg2) {
  return window['go']['gui']['App']['GetPTLine'](arg1, arg2);
}

export function GetPTLines(arg1) {
  return window['go']['gui']['App']['GetPTLines'](arg1);
}

export function GetPTLinesByMode(arg1, arg2) {
  return window['go']['gui']['App']['GetPTLinesByMode'](arg1, arg2);
}

export function GetPTRouteStops(arg1, arg2) {
  return window['go']['gui']['App']['GetPTRouteStops'](arg1, arg2);
}

export function GetPTRoutes(arg1, arg2) {
  return window['go']['gui']['App']['GetPTRoutes'](arg1, arg2);
}

export function GetPTStatistics(arg1) {
  return window['go']['gui']['App']['GetPTStatistics'](arg1);
}

export function GetPTStop(arg1, arg2) {
  return window['go']['gui']['App']['GetPTStop'](arg1, arg2);
}

export function GetPTStops(arg1) {
  return window['go']['gui']['App']['GetPTStops'](arg1);
}

export function GetPTStopsByBbox(arg1, arg2) {
  return window['go']['gui']['App']['GetPTStopsByBbox'](arg1, arg2);
}

export function GetPTTelemetry(arg1) {
  return window['go']['gui']['App']['GetPTTelemetry'](arg1);
}

export function GetPerson(arg1, arg2) {
  return window['go']['gui']['App']['GetPerson'](arg1, arg2);
}

export function GetPopulation(arg1) {
  return window['go']['gui']['App']['GetPopulation'](arg1);
}

export function GetPopulationByBbox(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['gui']['App']['GetPopulationByBbox'](arg1, arg2, arg3, arg4, arg5);
}

export function GetProcessTelemetry(arg1) {
  return window['go']['gui']['App']['GetProcessTelemetry'](arg1);
}

export function GetProcesses() {
  return window['go']['gui']['App']['GetProcesses']();
}

export function GetProcessesByFile(arg1) {
  return window['go']['gui']['App']['GetProcessesByFile'](arg1);
}

export function GetStartupConfig() {
  return window['go']['gui']['App']['GetStartupConfig']();
}

export function GetStartupFile() {
  return window['go']['gui']['App']['GetStartupFile']();
}

export function ProcessNetworkFile(arg1) {
  return window['go']['gui']['App']['ProcessNetworkFile'](arg1);
}

export function ProcessPTFile(arg1) {
  return window['go']['gui']['App']['ProcessPTFile'](arg1);
}

export function ProcessPopulationFile(arg1) {
  return window['go']['gui']['App']['ProcessPopulationFile'](arg1);
}

export function SelectFile() {
  return window['go']['gui']['App']['SelectFile']();
}

export function SetDatabase(arg1) {
  return window['go']['gui']['App']['SetDatabase'](arg1);
}

export function SyncChanges(arg1) {
  return window['go']['gui']['App']['SyncChanges'](arg1);
}
