// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {json} from '../models';

export function AddZoneToSession(arg1:string,arg2:string,arg3:Array<gui.Point>):Promise<void>;

export function AssignPopulationToZones(arg1:string):Promise<void>;

export function CheckProcessingStatus(arg1:number):Promise<string>;

export function ClearAllZones():Promise<void>;

export function CloseFilterSession(arg1:string):Promise<void>;

export function CountPersonsInPolygon(arg1:string,arg2:Array<gui.Point>):Promise<number>;

export function CreateDemoZones():Promise<void>;

export function CreateFilterSession(arg1:string):Promise<string>;

export function CreateNetworkLink(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateNetworkNode(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;

export function CreateZoneFromGeoJSON(arg1:Record<string, any>):Promise<void>;

export function DeleteNetworkLink(arg1:number,arg2:string):Promise<void>;

export function DeleteNetworkNode(arg1:number,arg2:string):Promise<void>;

export function DeleteZone(arg1:string):Promise<void>;

export function ExecuteAction(arg1:json.RawMessage):Promise<void>;

export function ExitApplication():Promise<void>;

export function ExportNetworkFile(arg1:number,arg2:string,arg3:Array<gui.BoundingBox>):Promise<void>;

export function ExportPTFile(arg1:number,arg2:string):Promise<void>;

export function ExportPTSubset(arg1:number,arg2:gui.BoundingBox,arg3:string):Promise<void>;

export function ExportPopulationFile(arg1:string,arg2:string):Promise<void>;

export function FindZoneForCoordinates(arg1:number,arg2:number):Promise<gui.Zone>;

export function GetAllZones():Promise<Array<gui.Zone>>;

export function GetDebugLogs():Promise<Record<string, string>>;

export function GetExportInfo(arg1:string):Promise<Record<string, any>>;

export function GetFilteredPopulationPage(arg1:string,arg2:number,arg3:number):Promise<gui.PaginatedResponse>;

export function GetLinksInBBox(arg1:number,arg2:Array<string>):Promise<Array<gui.LinkResult>>;

export function GetNodesInBBox(arg1:number,arg2:gui.BoundingBox):Promise<Array<gui.NodeResult>>;

export function GetPTDepartures(arg1:number,arg2:string):Promise<Array<gui.PTDeparture>>;

export function GetPTLine(arg1:number,arg2:string):Promise<gui.PTLine>;

export function GetPTLineSummaries(arg1:number,arg2:string):Promise<Array<gui.PTLineSummary>>;

export function GetPTLines(arg1:number):Promise<Array<gui.PTLine>>;

export function GetPTLinesByMode(arg1:number,arg2:string):Promise<Array<gui.PTLine>>;

export function GetPTRouteStops(arg1:number,arg2:string):Promise<Array<gui.PTRouteStop>>;

export function GetPTRoutes(arg1:number,arg2:string):Promise<Array<gui.PTRoute>>;

export function GetPTStatistics(arg1:number):Promise<Record<string, any>>;

export function GetPTStop(arg1:number,arg2:string):Promise<gui.PTStop>;

export function GetPTStops(arg1:number):Promise<Array<gui.PTStop>>;

export function GetPTTelemetry(arg1:number):Promise<gui.PTTelemetry>;

export function GetPerson(arg1:string,arg2:string):Promise<gui.Person>;

export function GetPersonsInPolygon(arg1:string,arg2:Array<gui.Point>,arg3:number,arg4:number):Promise<gui.PaginatedResponse>;

export function GetPopulation(arg1:string):Promise<Array<gui.Person>>;

export function GetPopulationByBbox(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<gui.Person>>;

export function GetPopulationByZones(arg1:string,arg2:number,arg3:number,arg4:Array<string>):Promise<gui.PaginatedResponse>;

export function GetPopulationPaginated(arg1:string,arg2:number,arg3:number,arg4:string):Promise<gui.PaginatedResponse>;

export function GetPopulationSimple(arg1:string,arg2:number,arg3:number):Promise<gui.PaginatedResponse>;

export function GetProcessTelemetry(arg1:number):Promise<gui.ProcessTelemetry>;

export function GetProcesses():Promise<Array<gui.Process>>;

export function GetProcessesByFile(arg1:string):Promise<Array<gui.Process>>;

export function GetStartupConfig():Promise<Record<string, any>>;

export function GetStartupFile():Promise<string>;

export function GetZone(arg1:string):Promise<gui.Zone>;

export function GetZoneStats(arg1:string):Promise<Record<string, any>>;

export function GetZonesWithCounts(arg1:string):Promise<Array<gui.ZoneCount>>;

export function LoadProcessData(arg1:gui.LoadingParams):Promise<Record<string, any>>;

export function ProcessNetworkFile(arg1:string):Promise<Record<string, any>>;

export function ProcessPTFile(arg1:string):Promise<gui.ProcessResult>;

export function ProcessPopulationFile(arg1:string):Promise<Record<string, any>>;

export function RemoveZoneFromSession(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveZone(arg1:gui.Zone):Promise<void>;

export function SelectFile():Promise<string>;

export function SetDatabase(arg1:gui.Database):Promise<void>;

export function StartProcessing(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SyncChanges(arg1:Array<json.RawMessage>):Promise<void>;

export function UpdateNetworkLink(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateNetworkNode(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;

export function ValidateNetworkXML(arg1:string):Promise<gui.ValidationResult>;

export function ValidatePTXML(arg1:string):Promise<gui.ValidationResult>;

export function ValidatePopulationXML(arg1:string):Promise<gui.ValidationResult>;

export function ValidateZoneBeforeAdd(arg1:string,arg2:Array<gui.Point>,arg3:number):Promise<Record<string, any>>;
