// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddPerson(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function CheckProcessingStatus(arg1:number):Promise<string>;

export function DeletePerson(arg1:string,arg2:string):Promise<Record<string, string>>;

export function DeleteProcess(arg1:number):Promise<void>;

export function GetPopulation(arg1:string):Promise<Array<database.Person>>;

export function GetProcesses():Promise<Array<database.Process>>;

export function GetProcessesByFile(arg1:string):Promise<Array<database.Process>>;

export function GetStartupFile():Promise<string>;

export function ProcessFile(arg1:string):Promise<Record<string, any>>;

export function UpdatePersonPlan(arg1:string,arg2:string,arg3:string):Promise<Record<string, string>>;
